Document: hd44780-i2c
Title: Debian hd44780-i2c Manual
Author: <insert document author here>
Abstract: This manual describes what hd44780-i2c is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hd44780-i2c/hd44780-i2c.sgml.gz

Format: postscript
Files: /usr/share/doc/hd44780-i2c/hd44780-i2c.ps.gz

Format: text
Files: /usr/share/doc/hd44780-i2c/hd44780-i2c.text.gz

Format: HTML
Index: /usr/share/doc/hd44780-i2c/html/index.html
Files: /usr/share/doc/hd44780-i2c/html/*.html
