Document: cuimhne-plugin
Title: Debian cuimhne-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what cuimhne-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cuimhne-plugin/cuimhne-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/cuimhne-plugin/cuimhne-plugin.ps.gz

Format: text
Files: /usr/share/doc/cuimhne-plugin/cuimhne-plugin.text.gz

Format: HTML
Index: /usr/share/doc/cuimhne-plugin/html/index.html
Files: /usr/share/doc/cuimhne-plugin/html/*.html
