#!/bin/bash -x
# postinst script for hd44780-i2c
#

echo $0 $1
set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
        dkms build hd44780-i2c/VERSION_STRING
        dkms install hd44780-i2c/VERSION_STRING
        sed -i 's/#dtparam=i2c_arm=on/dtparam=i2c_arm=on/g' /boot/config.txt
        dtparam i2c_arm=on
        modprobe i2c_dev
        ln -sf "/etc/lcd/lcd.service" "/etc/systemd/system/lcd.service"
        chmod ugo+x /etc/lcd/lcd_setup.sh
        systemctl start lcd
        systemctl enable lcd
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


exit 0
