#!/bin/bash -x
# postinst script for hd44780-i2c
#

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
        if [[ 1 -ne `grep -c "^lcd:" /etc/group` ]]
        then
            echo "Creating lcd group"
            addgroup --system lcd
        else
            echo "lcd group already exists"
        fi
        if [ -n "${KERNEL_VERSION}" ]
        then
           DKMS_ARG="-k ${KERNEL_VERSION} -a armv6l"
        fi
        dkms build ${DKMS_ARG} hd44780-i2c/VERSION_STRING
        dkms install ${DKMS_ARG}  hd44780-i2c/VERSION_STRING
        sed -i 's/#dtparam=i2c_arm=on/dtparam=i2c_arm=on/g' /boot/config.txt        
        ln -sf "/etc/lcd/lcd.service" "/etc/systemd/system/lcd.service"
        ln -sf "/etc/lcd/whichlcd" "/usr/bin/whichlcd"
        chgrp -R lcd /etc/lcd
        chmod ug+x /etc/lcd/lcd_setup.sh
        chmod ugo+x /etc/lcd/whichlcd
        systemctl enable lcd
        systemctl start lcd
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


exit 0
