#!/bin/sh -x
# preinst script for hd44780-i2c

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
	install)
    ;;
    
    upgrade)
        set +e
        systemctl is-active --quiet lcd
        if [ $? -ne 0 ]
        then 
            set -e
            systemctl stop lcd
        fi
        set -e
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


exit 0
