#!/bin/sh -x
# prerm script for hd44780-i2c

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    remove|upgrade|deconfigure)
    	systemctl is-active --quiet lcd
        if [ $? -ne 0 ]
        then 
            systemctl stop lcd
        fi
        if [ -f /etc/lcd/lcd.service ]
        then
            systemctl disable lcd
        fi
        if [ `dkms status hd44780-i2c/VERSION_STRING | wc -l` -gt 0 ]
        then
            dkms remove hd44780-i2c/VERSION_STRING --all
        fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


exit 0
